version: '3.4'

tasks:
  install:
    cmds:
      - python -m venv ./venv
      - ./venv/bin/pip install -r requirements.txt
  insert:
    cmds:
      - ./venv/bin/python ./src/insert.py

  query:
    cmds:
      - ./venv/bin/python ./src/query.py