[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "localsearch-grpc"
version = "0.0.0"
authors = [
  {name = "Benjamin Sivoravong", email = "bensivo@gmail.com"}
]