version: '3.4'

tasks:
  install:
    cmds:
      - poetry install
    
  generate:
    cmds:
      - task: install
      - poetry run python -m grpc_tools.protoc -I../grpc-proto --python_out=./localsearch_grpc --pyi_out=./localsearch_grpc --grpc_python_out=./localsearch_grpc ../grpc-proto/localsearch.proto

      # See: https://github.com/protocolbuffers/protobuf/issues/2283 and https://github.com/protocolbuffers/protobuf/issues/7061
      # Protoc generates a flat folder of files, assuming that the root of the that folder is importable from the rest of the project.
      # In our monorepo, we want this generated code to be found under the module "localsearch_grpc", so we must rewrite the generated import statements to conform to that.
      # - sed -i ''  's/import localsearch_pb2 as localsearch__pb2/from localsearch_grpc import localsearch_pb2 as localsearch__pb2/g' ./localsearch_grpc/localsearch_pb2_grpc.py
      - sed -i '' 's/import \(.*\) as/from . import \1 as/' ./localsearch_grpc/localsearch_pb2_grpc.py


  build:
    cmds:
      - poetry build