version: '3.4'

tasks:
  install:
    cmds:
      - python -m venv ./venv
      - ./venv/bin/pip install -r requirements.txt
    
  generate:
    cmds:
      - |
        ./venv/bin/python -m grpc_tools.protoc -I../proto --python_out=./src --pyi_out=./src --grpc_python_out=./src ../proto/localsearch.proto