version: '3.4'

includes:
  grpc: 
    taskfile: ../grpc-python/Taskfile.yml
    dir: ../grpc-python
    internal: true

tasks:
  install:
    cmds:
      - task: grpc:generate
      - poetry install

  run:
    cmds:
      - poetry run pytest
