version: '3.4'

includes:
  localsearch_grpc: 
    taskfile: ../localsearch_grpc/Taskfile.yml
    dir: ../localsearch_grpc
    internal: true
  localsearch_server: 
    taskfile: ../localsearch_server/Taskfile.yml
    dir: ../localsearch_server
    internal: true

tasks:
  install:
    cmds:
      - task: localsearch_grpc:build
      - rm -rf ./deps && mkdir ./deps
      - cp ../../dist/localsearch_grpc-0.0.0-py3-none-any.whl ./deps
      - poetry install

  run:
    cmds:
      - poetry run pytest

  docker:
    cmds:
      - task: install
      - docker run -d --net localsearch --hostname localsearch-server --name localsearch-server localsearch-server
      - docker build -t localsearch-e2e .

  docker-run:
    cmds:
      - task: localsearch_server:docker
      - task: docker
      - docker run --net localsearch -e LOCALSEARCH_SERVER=localsearch-server --name localsearch-e2e localsearch-e2e 
      - docker rm -f localsearch-server localsearch-e2e