version: '3.4'

tasks:
  install:
    cmds:
      - go mod tidy
    
  generate:
    cmds:
      - task: install
      - |
        protoc --proto_path=../proto \
        --go_out=./pkg/grpc --go_opt=paths=source_relative \
        --go-grpc_out=./pkg/grpc --go-grpc_opt=paths=source_relative \
        ../proto/localsearch.proto
