# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import localsearch_pb2 as localsearch__pb2


class LocalsearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertDocument = channel.unary_unary(
                '/localsearch.Localsearch/InsertDocument',
                request_serializer=localsearch__pb2.InsertDocumentRequest.SerializeToString,
                response_deserializer=localsearch__pb2.InsertDocumentResponse.FromString,
                )
        self.GetDocument = channel.unary_unary(
                '/localsearch.Localsearch/GetDocument',
                request_serializer=localsearch__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=localsearch__pb2.GetDocumentResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/localsearch.Localsearch/Query',
                request_serializer=localsearch__pb2.QueryRequest.SerializeToString,
                response_deserializer=localsearch__pb2.QueryResponse.FromString,
                )


class LocalsearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalsearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDocument,
                    request_deserializer=localsearch__pb2.InsertDocumentRequest.FromString,
                    response_serializer=localsearch__pb2.InsertDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=localsearch__pb2.GetDocumentRequest.FromString,
                    response_serializer=localsearch__pb2.GetDocumentResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=localsearch__pb2.QueryRequest.FromString,
                    response_serializer=localsearch__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'localsearch.Localsearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Localsearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/localsearch.Localsearch/InsertDocument',
            localsearch__pb2.InsertDocumentRequest.SerializeToString,
            localsearch__pb2.InsertDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/localsearch.Localsearch/GetDocument',
            localsearch__pb2.GetDocumentRequest.SerializeToString,
            localsearch__pb2.GetDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/localsearch.Localsearch/Query',
            localsearch__pb2.QueryRequest.SerializeToString,
            localsearch__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
