[tool.poetry]
name = "localsearch_server"
version = "0.0.1"
description = ""
authors = ["Ben Sivoravong <bensivo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asyncio = "^3.4.3"
grpcio = "^1.62.1"
nltk = "^3.8.1"
numpy = "^1.26.4"
protobuf = "^4.25.3"
localsearch-grpc = {path = "../grpc-python", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
