version: '3.4'

includes:
  grpc-python: 
    taskfile: ../grpc-python/Taskfile.yml
    dir: ../grpc-python
    internal: true

tasks:
  install:
    cmds:
      - poetry install
  run:
    cmds:
      - poetry run python ./src/main.py