version: '3.4'

includes:
  localsearch_grpc: 
    taskfile: ../localsearch_grpc/Taskfile.yml
    dir: ../localsearch_grpc
    internal: true

tasks:
  install:
    cmds:
      - task: localsearch_grpc.build
      - poetry install
  run:
    cmds:
      - poetry run python ./src/main.py