version: '3.4'

includes:
  grpc: 
    taskfile: ../grpc/Taskfile.yml
    dir: ../grpc
    internal: true

tasks:
  install:
    cmds:
      - task: grpc:generate
      - poetry install

  run:
    cmds:
      - poetry run python -m localsearch_server.main
