version: '3.4'

includes:
  grpc: 
    taskfile: ../grpc/Taskfile.yml
    dir: ../grpc
    internal: true
  server: 
    taskfile: ../server/Taskfile.yml
    dir: ../server
    internal: true

tasks:
  install:
    cmds:
      - task: grpc:generate
      - poetry install

  insert:
    cmds:
      - poetry run python ./localsearch_eval/insert.py

  query:
    cmds:
      - poetry run python ./localsearch_eval/query.py